name: Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set lower case owner name
        run: |
          echo "owner_lc=${OWNER,,}" >>${GITHUB_ENV}
          echo "${GITHUB_ENV}"
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cat_weight_tracker:latest

      - name: Configure Docker for GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.owner_lc }}/cat_weight_tracker:latest